### ISSUE TITLE
Auto feature (renaming layer) doesn't work with Symbols

### ISSUE THREAD

**Issue by CGuindon** [paintedbicycle/sketch-data-faker#1]
Steps to Reproduce:

1. Create symbol with text
2. rename text layer name.jobTitle
3. Select layer and Run Data Faker plugin Auto layer name
4. on the artboard, try to refresh data on the symbol 
5. Error modal pops up

**Comment by paintedbicycle** [comment]
Thanks for reporting. Just reproduced this. Investigating

**Comment by paintedbicycle** [comment]
Just pushed out Release 0.1.9 https://github.com/paintedbicycle/sketch-data-faker/releases/tag/v0.1.9 that should fix the issue

Commit https://github.com/paintedbicycle/sketch-data-faker/commit/2635f9da631202859fc7e1fe59c71f47df6ca60a

Thanks!

Paul
