### ISSUE TITLE
Doesn't seem to work on Sketch 57.1

### ISSUE THREAD

**Issue by dorian-grey** [paintedbicycle/sketch-data-faker#10]

**Comment by paintedbicycle** [comment]
Hi @dorian-grey can you please describe what you tried and what didn't work?

- Did it not install at all?
- Did it now show itself in the menu?
- Did it not allow the insertion of text into a text layer? On a symbol? 
etc

This is a free plugin that I released to the community and so anything you can do on your end to save me some time would be appreciated

**Comment by dorian-grey** [comment]
Excuse my brevity: Often plugins are abandoned or it's already a known issue that a Sketch update broke them. Therefore I didn't want to waste time in case this applied here.

Embarrassingly, everything works fine anyway: I mis-read the readme and didn't understand, that you had to first select the auto layer name from Plugins > Sketch Data Faker, and then activate the auto population using right click (on the text layer) > Data.

Everything looking good now! :)

**Comment by paintedbicycle** [comment]
Great. Glad to hear it's working for you.

There is an open issue with symbols (https://github.com/paintedbicycle/sketch-data-faker/issues/9) that I'll look into soon. I just changed jobs and haven't had time. But otherwise most things should be working.
