### ISSUE TITLE
Doesn’t work with library symbol overrides

### ISSUE THREAD

**Issue by timohofmeijer** [paintedbicycle/sketch-data-faker#8]
To reproduce, add any library symbol with a text override to a new document and try to apply faker data to it.

Tested this in Sketch 54.

**Comment by paintedbicycle** [comment]
Thanks for reporting this. I haven't tested with layers from external libraries, so you may be right that it's a bug in `Sketch Data Faker`. I'll take a look.

Can you tell me one thing though - have you used regular "Sketch Data" on a layer imported from a Library? And does that work? So, if you do exactly the same thing you tried with `Sketch Data Faker`, but instead you choose "Data -> Sketch Data -> Names" - will that work on the same layer that `Sketch Data Faker` is not?

Thanks!

**Comment by timohofmeijer** [comment]
Yes, I tested this, other Sketch Data does work as expected when overriding value with data on library symbol instances.

**Comment by paintedbicycle** [comment]
Ok great. Hopefully they expose the ability to set this in the API. I will take a look this weekend. If it's possible to fix, it should be done in a few days.

**Comment by paintedbicycle** [comment]
Hi @timohofmeijer I did some debugging this weekend and recreated your issue.

There are two separate things here

1. `sketch-data-faker` is not finding the correct layer. I do a check here https://github.com/paintedbicycle/sketch-data-faker/blob/master/src/faker.js#L25 that currently toggles between either a normal layer, or, in the case of a symbol, it uses the symbol instead. It looks like I need to add another check here for `library instances`. I thought it would already be taken care of, but apparently not. I'll have to research a little more to get this working.

2. One potential issue is with `Automatic Mode` which uses the layer name. I'm not certain you can rename layers inside `libraries` that you've imported. Do you know if that's true?

So I can likely get the `Manual` mode, with quick overrides working, but it might be hard to get the full automatic mode working unless the Sketch user has the ability to edit the names of the original library layer. Anyway, more research needs to be done...perhaps I can indeed change the layer name programatically. Not sure.

I'll keep going on this next weekend.

**Comment by timohofmeijer** [comment]
Hi Paul, grateful for your efforts! One could of course rename layers in a self managed library. With an external library (e.g. iOS) this would require a fork and is likely not desirable. I personally would prefer applying data manually even though I manage the library myself. I could fork and have a look at the code this weekend, if you could let me know if you are not already on this, so we don't spend duplicate time : )

**Comment by paintedbicycle** [comment]
@timohofmeijer Just pushed a version live for testing. You should now be able to override the text in a library layer using Manual mode.

Automatic mode works too, but it sets the layer name on the parent. This is the only editable layer name and actually happens automatically. However, since the layer that gets the new content is only the layer that is selected, it updates the correct layer with the text.

I'll have to investigate more, but let me know what you think

**Comment by paintedbicycle** [comment]
Hi @timohofmeijer I broke Library symbol overrides in a previous release, sorry about that. It is now fixed with 0.7.0. If you're still using it, I'd love to hear if it worked for you.

Thanks!
